apiVersion: batch/v1
kind: Job
metadata:
  generateName: notification-postsync-
  annotations:
    argocd.argoproj.io/hook: PostSync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: log-notification
        image: alpine
        command:
        - "/bin/sh"
        - "-c"
        - "echo 'La synchronisation a réussi.'"
      restartPolicy: Never
